name: result_extensions
description: Useful extensions on Result class of async package.
version: 0.2.0
repository: https://github.com/veloce/result_extensions

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  async: ^2.10.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
